ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.SerializationKt.configureSerialization
      - com.ExposedKt.configureExposed
      - com.SecurityKt.configureSecurity
      - com.ResourcesKt.configureResources
      - com.RoutingKt.configureRouting
      - com.HTTPKt.configureHTTP